# Generated by Django 5.2.1 on 2025-05-17 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('triCode', models.CharField(max_length=3)),
                ('teamLogo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('heightInInches', models.IntegerField(blank=True, null=True)),
                ('heightInCentimeters', models.IntegerField(blank=True, null=True)),
                ('weightInPounds', models.IntegerField(blank=True, null=True)),
                ('weightInKilograms', models.IntegerField(blank=True, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('birthCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('shootsCatches', models.CharField(blank=True, max_length=10, null=True)),
                ('isActive', models.CharField(choices=[('True', 'Active'), ('False', 'Inactive')], default='True', max_length=5)),
                ('sweaterNumber', models.CharField(blank=True, max_length=3, null=True)),
                ('currentTeamID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.team')),
            ],
            options={
                'ordering': ['-playerId'],
            },
        ),
    ]
